#[x,y,theta]
home: [0, 0, 0]
kitchen_fridge: [4.663, 1.941, -1.026]
kitchen_tabletop: [5.058, 1.837, -0.919]
door_side: [1.224, -0.655, -2.303]
door_front: [0.153, -0.288, -1.560]
table_right_offer: [-1.459, 2.409, 0.895]
table_right_unload: -1.481, 2.416, 1.628]
table_left_offer: [0.443, 2.513, 2.286]
table_left_unload: [-0.446, 1.796, -3.064]
